#!/bin/bash
#script is used to ajust volume of sink(s)
#it checks for available sinks and adjust them all based on input parameter
#put it into $PATH so i3config could use

#arg: <+/-><vol>% or toggle
[ "$#" -eq 1 ] && vol=$1 || return

#choose command
set_sink=$([ "$vol" == "toggle" ] && echo "set-sink-mute" || echo "set-sink-volume")

#store indices in an array in case of multiple sinks available
sink_idx=( $(pactl list short sinks | cut -f1) )

#attempt changing volume of sinks
for idx in ${sink_idx[@]}; do
    pactl $set_sink $idx $vol
done
