#!/bin/bash

#Exit immediately if a simple command exits with non-zero status
set -e

#Get project directory
dir=$(git rev-parse --show-toplevel)

#Create a lock
if [ -f $dir/lock.tags ]; then
	echo "already processing ctags"; exit 0
else
	touch "$dir/lock.tags"
fi

#Remove lock after finished
#Note: trap [cmds] [sigs] => cmds are executed if sigs are catched
trap 'rm -f "$dir/lock.tags"; rm -f "$dir/$$.tags"' EXIT

#Create tags
#Note: other default parameters are in $HOME/.ctags
#Note: $$ is current process id. Using $$.tags as temporary file
git ls-files | ctags --tag-relative -L - -f "$dir/$$.tags"
mv "$dir/$$.tags" "$dir/.tags"
